
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author":"brad",  
    "likes":5,
    "title":"the brad man",
    "url": "http://brad.com",
    "userId":"65361e0a7da9971f94a27181"
}